# Generated by Django 5.2.17 on 2026-09-17 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique name of the department (e.g. Engineering, Sales).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text="Optional description of the department's responsibilities.")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the department was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the department was last updated.')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the team member.', max_length=150)),
                ('email', models.EmailField(db_index=True, help_text='Corporate email address used for login and notifications.', max_length=255, unique=True)),
                ('avatar', models.ImageField(blank=True, help_text='Profile avatar image for the user.', null=True, upload_to='avatars/')),
                ('giving_allowance', models.PositiveIntegerField(default=100, help_text='Monthly/periodic points allowance available to award kudos to peers.')),
                ('earned_points', models.PositiveIntegerField(default=0, help_text='Total accumulated points received through peer appreciation kudos.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the Django admin site.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the user account was registered.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the user account was last modified.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, help_text='Department/team the user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.department')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='idx_user_email'), models.Index(fields=['department'], name='idx_user_department'), models.Index(fields=['created_at'], name='idx_user_created_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('giving_allowance__gte', 0)), name='check_positive_giving_allowance'), models.CheckConstraint(condition=models.Q(('earned_points__gte', 0)), name='check_positive_earned_points')],
            },
        ),
    ]
