# Generated by Django 5.2.17 on 2026-09-17 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kudos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('+1', '+1'), ('👏', '👏'), ('🔥', '🔥')], db_index=True, help_text='Emoji reaction symbol (+1, 👏, 🔥).', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the reaction was added.')),
                ('kudo', models.ForeignKey(help_text='The Kudo card being reacted to.', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='kudos.kudos')),
                ('user', models.ForeignKey(help_text='The team member reacting to the Kudo.', on_delete=django.db.models.deletion.CASCADE, related_name='kudo_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
                'db_table': 'reactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kudo', 'reaction_type'], name='idx_reaction_kudo_type'), models.Index(fields=['user', 'created_at'], name='idx_reaction_user_created')],
                'constraints': [models.UniqueConstraint(fields=('kudo', 'user', 'reaction_type'), name='unique_user_kudo_reaction_type')],
            },
        ),
    ]
