# Generated by Django 5.2.17 on 2026-09-17 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kudos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('points', models.PositiveSmallIntegerField(choices=[(10, '10 Points'), (20, '20 Points'), (50, '50 Points')], help_text='Points awarded with the kudo (10, 20, or 50).')),
                ('message', models.TextField(help_text='Appreciation message explaining what the receiver achieved.', validators=[django.core.validators.MinLengthValidator(5, message='Kudos message must be at least 5 characters long.'), django.core.validators.MaxLengthValidator(1000, message='Kudos message cannot exceed 1000 characters.')])),
                ('company_value', models.CharField(choices=[('Teamwork', 'Teamwork'), ('CustomerObsession', 'Customer Obsession'), ('Innovation', 'Innovation')], db_index=True, help_text='Company value / tag highlighted by this appreciation.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the kudo was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the kudo was last modified.')),
                ('receiver', models.ForeignKey(help_text='Registered peer receiving the recognition.', on_delete=django.db.models.deletion.CASCADE, related_name='received_kudos', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='Authenticated user sending the recognition.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_kudos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kudo',
                'verbose_name_plural': 'Kudos',
                'db_table': 'kudos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(help_text='Number of points transferred in this transaction.', validators=[django.core.validators.MinValueValidator(1, message='Transaction amount must be at least 1 point.')])),
                ('transaction_type', models.CharField(choices=[('KUDO_TRANSFER', 'Kudos Point Transfer'), ('ALLOWANCE_REPLENISHMENT', 'Monthly Allowance Replenishment'), ('ADMIN_ADJUSTMENT', 'Administrative Adjustment')], db_index=True, default='KUDO_TRANSFER', help_text='Nature of the point transaction.', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the transaction was executed.')),
                ('kudo', models.ForeignKey(blank=True, help_text='Kudo associated with this point movement, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='kudos.kudos')),
                ('receiver', models.ForeignKey(help_text='User whose points balance was credited.', on_delete=django.db.models.deletion.CASCADE, related_name='received_point_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='User whose giving allowance was debited (null for system grants).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'db_table': 'point_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kudos',
            index=models.Index(fields=['sender', 'created_at'], name='idx_kudos_sender_created'),
        ),
        migrations.AddIndex(
            model_name='kudos',
            index=models.Index(fields=['receiver', 'created_at'], name='idx_kudos_receiver_created'),
        ),
        migrations.AddIndex(
            model_name='kudos',
            index=models.Index(fields=['company_value'], name='idx_kudos_company_value'),
        ),
        migrations.AddConstraint(
            model_name='kudos',
            constraint=models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='check_kudos_sender_not_receiver'),
        ),
        migrations.AddConstraint(
            model_name='kudos',
            constraint=models.CheckConstraint(condition=models.Q(('points__in', [10, 20, 50])), name='check_kudos_valid_points'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['sender', 'created_at'], name='idx_tx_sender_created'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['receiver', 'created_at'], name='idx_tx_receiver_created'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['transaction_type'], name='idx_tx_type'),
        ),
    ]
